# Create new heros from here.
POST /api/hero-post HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"heroName":"Tom Brady with Tampa Bay","heroUltimate":"Retire many times","imageUrl":"https://i.imgur.com/kFPrWNl.jpeg"}