# Create new heros from here.
POST /api/hero-post HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"name":"Tom Brady with New England","ultimate":"Retire many times","photoUrl":"https://i.imgur.com/kFPrWNl.jpeg"}