PUT  /api/hero-post/1/like HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18ydDE3TEJQWklXV3BucWR1aUNiUXhEcEdJNGYiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjIwMjg4MDEyOTMsImlhdCI6MTc0NDQxODkwMSwiaXNzIjoiaHR0cHM6Ly9mbGVldC1raXQtOTUuY2xlcmsuYWNjb3VudHMuZGV2IiwianRpIjoiMzcwMTFlNWM4Y2MwMjlhNmI4YTEiLCJuYmYiOjE3NDQ0MTg4OTYsInN1YiI6InVzZXJfMnQ5RzFwSm1QY01PeE1VVXpvZzRrbXlaSG95In0.VsAlqufrdVD8EpwkoTj74iw2hQ1VjP-DxkxoztmavFRPvZle8Kbe5Md2V1aR86nyB2VQXKTXrzAoHN7g4Y9sOe4333w3XafHsxjoVdkTFZy2gbXuGh3sx2J7_YZ398eVQo7ap-NjFTtitMZa3ja1puGKNqvNzF_juqDeSR60fhvIHYNa8oFs2R5-aWxJYGlNUPM8lwLh0xtZHzLwlAM1-vSMzGbTazs6x_tFwCmrb_iESt9HtOALnJLVI6livx_mlZYa9OmnlaI_J6ii0I3u0nxeuKnNV8toYYzqek5gQGnA5b4GQaBUq5LloNuX9EsEMXgS49FAjkA6ZL3c1qhFkA