# Update pre-existing heroes from here.
PUT /api/hero-post/1 HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"name":"Tom Brady with a baseball team","ultimate":"Retire many times","photoUrl":"https://i.imgur.com/kFPrWNl.jpeg"}